/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.73
 * Generated at: 2019-07-04 09:03:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("   \r\n");
  
	String oriurl = (String)request.getAttribute("oriurl");
	String shorten_url = (String)request.getAttribute("resurl");

	if(oriurl == null) oriurl = "";
	if(shorten_url == null) shorten_url = "";
	//String strImagePath = getServletContext().getRealPath("").replace("\\", "/") ;//+ "/WEB-INF/images/kakao.jpg";
	String strImagePath =  request.getSession().getServletContext().getRealPath("/").replace("\\", "/")+"img/kakao.jpg";



      out.write("\r\n");
      out.write("\r\n");
      out.write("<style type = \"text/css\">\r\n");
      out.write("@import url(//fonts.googleapis.com/earlyaccess/nanumgothic.css);\r\n");
      out.write("body { \r\n");
      out.write("    \r\n");
      out.write("    min-height: 100%;\r\n");
      out.write("    background-position: center;\r\n");
      out.write("    background-display:block ;\r\n");
      out.write("    background-size: cover;\r\n");
      out.write("    background-repeat: no-repeat;\r\n");
      out.write("    background-color : yellow;\r\n");
      out.write("}\r\n");
      out.write("</style> \r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<script language =\"javascript\">\r\n");
      out.write("function shorten_click() {\r\n");
      out.write("\r\n");
      out.write("\tvar origin_url = document.writeform.origin_url.value ;\r\n");
      out.write("\t\r\n");
      out.write("\tif(origin_url==\"\"){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\talert(\"주소를 입력하세요.\");\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tvar form = document.writeform;\r\n");
      out.write("\tform.action = \"/getUrlServlet\";\r\n");
      out.write("\t//f.method = \"get\";\r\n");
      out.write("\tform.submit();\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("function goWebsite() {\r\n");
      out.write("\t\r\n");
      out.write("\tvar url= document.writeform.shorten_url.value;\r\n");
      out.write("\turl = \"http://\" +  url;\r\n");
      out.write("\twindow.open(url,\"popup\",\"width=1000, height=700, location=yes\");\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<h1 align = \"center\" style=\"font-family:Nanum Gothic\">단축URL 생성서비스</h1>\r\n");
      out.write("<form method=\"post\" action=\"urlShorten/UrlShortenMakeServlet\" name=\"writeform\">\r\n");
      out.write("\t<h1 align = \"center\" style=\"font-family:Nanum Gothic\"> 원본URL \r\n");
      out.write("\t<input type =\"text\" name= \"origin_url\" value=\"");
      out.print( oriurl );
      out.write("\">\r\n");
      out.write("\t<input type =\"button\" style=\"width:100; font-family:Nanum Gothic ; \" value=\"shorten\" onclick=\"shorten_click()\" /></h1>\r\n");
      out.write("\t\r\n");
      out.write("\t<h1 align = \"center\" style=\"font-family:Nanum Gothic\"> 단축URL <input type =\"text\" name= \"shorten_url\" value=\"");
      out.print( shorten_url );
      out.write("\">\r\n");
      out.write("\t<input type =\"button\" style=\"width:100; font-family:Nanum Gothic\" value=\"goWebsite\" onclick=\"goWebsite()\"/></h1>\r\n");
      out.write("\t\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
