/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.73
 * Generated at: 2019-07-01 13:38:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.urlShorten.UrlShortenMakeServlet;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("      \r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<script language =\"javascript\">\r\n");
      out.write("function shorten_click() {\r\n");
      out.write("\t\r\n");
      out.write("\tvar origin_url = document.writeform.oriurl.value ;\r\n");
      out.write("\talert(111);\r\n");
      out.write("\t\r\n");
      out.write("\tvar form = document.writeform;\r\n");
      out.write("\tform.action = \"./UrlShortenMakeServlet.do\";\r\n");
      out.write("\t//f.method = \"get\";\r\n");
      out.write("\tform.submit();\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t//document.writeform.shorten_url.value = ");
      out.print( request.getAttribute("result") );
      out.write(";\r\n");
      out.write("\t//document.writeform.shorten_url.value =112;\r\n");
      out.write("\talert(222);\r\n");
      out.write("\t//alert(request.getAttribute(\"result\"));\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<h1 align = \"center\">main</h1>\r\n");
      out.write("<form method=\"\" action=\"urlShorten/UrlShortenMakeServlet\" name=\"writeform\">\r\n");
      out.write("\t<h1 align = \"center\"> 원본link \r\n");
      out.write("\t<input type =\"text\" name= \"oriurl\" value=\"https://www.google.com/\">\r\n");
      out.write("\t<input type =\"button\" value=\"shorten\" onclick=\"shorten_click()\"/></h1>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<br/>\r\n");
      out.write("\t<h1 align = \"center\"> 변경link <input type =\"text\" name= \"shorten_url\" value=\"\"> <br /></h1>\r\n");
      out.write("\t");
      out.print( request.getAttribute("result") );
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
